### Creating from list/tuples

In [1]:
import numpy as np

In [2]:
# From lists, tuples
print(np.array([23,45,23,45,23]))

[23 45 23 45 23]


In [3]:
print(np.array((2.3,4.5,6.7,8.9)))

[2.3 4.5 6.7 8.9]


In [4]:
# size depends on data-type, small numbers would consume lesser space as compared to plain python lists
from sys import getsizeof as size
the_list = [23,12,34,45,56,67,34,12,34,55]
empty_array_size = size(np.array([]))

In [5]:
for data_type in (np.int8,np.int16,np.int32,np.int64,np.float):
    print(f"size for type {data_type.__name__} = {size(np.array(the_list,data_type))-empty_array_size}")

size for type int8 = 10
size for type int16 = 20
size for type int32 = 40
size for type int64 = 80
size for type float = 80


### Creating from ranges

In [6]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(np.arange(-5,5))

[-5 -4 -3 -2 -1  0  1  2  3  4]


In [8]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [9]:
print(np.arange(0.2,2,0.5))

[0.2 0.7 1.2 1.7]


In [10]:
print(np.arange(0.5, 6.3, 0.7))

[0.5 1.2 1.9 2.6 3.3 4.  4.7 5.4 6.1]


In [11]:
print(np.arange(0.5, 6.3, 0.7,int))

[0 1 2 3 4 5 6 7 8]


### Uniformly spaced samples in a range : linspace

In [12]:
print(np.linspace(1,50)) # by default number of samples is 50

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [13]:
for i in range(1,12):
    print(i,np.linspace(0,24,i))

1 [0.]
2 [ 0. 24.]
3 [ 0. 12. 24.]
4 [ 0.  8. 16. 24.]
5 [ 0.  6. 12. 18. 24.]
6 [ 0.   4.8  9.6 14.4 19.2 24. ]
7 [ 0.  4.  8. 12. 16. 20. 24.]
8 [ 0.          3.42857143  6.85714286 10.28571429 13.71428571 17.14285714
 20.57142857 24.        ]
9 [ 0.  3.  6.  9. 12. 15. 18. 21. 24.]
10 [ 0.          2.66666667  5.33333333  8.         10.66666667 13.33333333
 16.         18.66666667 21.33333333 24.        ]
11 [ 0.   2.4  4.8  7.2  9.6 12.  14.4 16.8 19.2 21.6 24. ]


In [14]:
# return the distance between two consecutive samples
# i is number of equi-distant samples required
# formula to get distance(d) between two consecutive samples between H and L  : (H-L)/i-1
# i-1 : because for i points there would be i-1 intervals
# Then the points would be : L, L+d, L+2d, L+3d, ..., H
for i in range(1,12):
    values = np.linspace(0,24,i,retstep=True)
    print(f"step = {i}\tdistance={values[1]}\tvalues={values[0]}")


step = 1	distance=nan	values=[0.]
step = 2	distance=24.0	values=[ 0. 24.]
step = 3	distance=12.0	values=[ 0. 12. 24.]
step = 4	distance=8.0	values=[ 0.  8. 16. 24.]
step = 5	distance=6.0	values=[ 0.  6. 12. 18. 24.]
step = 6	distance=4.8	values=[ 0.   4.8  9.6 14.4 19.2 24. ]
step = 7	distance=4.0	values=[ 0.  4.  8. 12. 16. 20. 24.]
step = 8	distance=3.4285714285714284	values=[ 0.          3.42857143  6.85714286 10.28571429 13.71428571 17.14285714
 20.57142857 24.        ]
step = 9	distance=3.0	values=[ 0.  3.  6.  9. 12. 15. 18. 21. 24.]
step = 10	distance=2.6666666666666665	values=[ 0.          2.66666667  5.33333333  8.         10.66666667 13.33333333
 16.         18.66666667 21.33333333 24.        ]
step = 11	distance=2.4	values=[ 0.   2.4  4.8  7.2  9.6 12.  14.4 16.8 19.2 21.6 24. ]


In [15]:
# endpoint = False : Don't include the end point in array, but refer it while counting the distance
# i is number of equi-distant samples required
# formula to get distance(d) between two consecutive samples between H and L  : (H-L)/i
# i : because for i points there would be i-1 intervals, but now we need to exclude the endpoint so i-1+1 = i
# Then the points would be : L, L+d, L+2d, L+3d, ...
for i in range(1,12):
    values = np.linspace(0,24,i,retstep=True,endpoint=False)
    print(f"step = {i}\tdistance={values[1]}\tvalues={values[0]}")

step = 1	distance=nan	values=[0.]
step = 2	distance=12.0	values=[ 0. 12.]
step = 3	distance=8.0	values=[ 0.  8. 16.]
step = 4	distance=6.0	values=[ 0.  6. 12. 18.]
step = 5	distance=4.8	values=[ 0.   4.8  9.6 14.4 19.2]
step = 6	distance=4.0	values=[ 0.  4.  8. 12. 16. 20.]
step = 7	distance=3.4285714285714284	values=[ 0.          3.42857143  6.85714286 10.28571429 13.71428571 17.14285714
 20.57142857]
step = 8	distance=3.0	values=[ 0.  3.  6.  9. 12. 15. 18. 21.]
step = 9	distance=2.6666666666666665	values=[ 0.          2.66666667  5.33333333  8.         10.66666667 13.33333333
 16.         18.66666667 21.33333333]
step = 10	distance=2.4	values=[ 0.   2.4  4.8  7.2  9.6 12.  14.4 16.8 19.2 21.6]
step = 11	distance=2.1818181818181817	values=[ 0.          2.18181818  4.36363636  6.54545455  8.72727273 10.90909091
 13.09090909 15.27272727 17.45454545 19.63636364 21.81818182]


### Array Dimensions : 
<b>Idea : better think in terms of a tree, an array with shape (3,4,5) : 3 nodes at level 2, 3 \* 4 nodes at level 3, 3 \* 4 \* 5 nodes at level 4
TODO : insert a tree figure here

In [16]:
# 0 dimensions : a scaler value : no axis : A tree with a single root node
zd_array = np.array(3)
print("Array:",zd_array)
print("Dimensions:", np.ndim(zd_array))
print("Data Type:", zd_array.dtype)
print("Shape: ",zd_array.shape)

Array: 3
Dimensions: 0
Data Type: int64
Shape:  ()


In [17]:
# 1 dimension : only x-axis : A 2 level tree
one_d_array = np.array([2,3,5,6])
print("Array:",one_d_array)
print("Dimensions:", np.ndim(one_d_array))
print("Data Type:", one_d_array.dtype)
print("Shape: ",one_d_array.shape)

Array: [2 3 5 6]
Dimensions: 1
Data Type: int64
Shape:  (4,)


In [18]:
# 2 dimensions : x and y axis : A 3 level tree
two_d_array = np.array([
    [2,3,5,6,8],
    [1,2,0,4,9],
    [7,4,1,6,-1]
])
print("Array:",two_d_array)
print("Dimensions:", np.ndim(two_d_array))
print("Data Type:", two_d_array.dtype)
print("Shape: ",two_d_array.shape)

Array: [[ 2  3  5  6  8]
 [ 1  2  0  4  9]
 [ 7  4  1  6 -1]]
Dimensions: 2
Data Type: int64
Shape:  (3, 5)


In [19]:
# 3 dimensions : x,y and z axis : A 4 level tree
three_d_array = np.array([
    # z[0]
    [
        # y[0]
        [2,3,5,6,8],# x[0]=2, x[1]=3, ... x[4]=8
        # y[1]
        [1,2,0,4,9],
        # y[2]
        [7,4,1,6,-1]
    ],
    # z[1]
    [
        [6,1,5,6,8],
        [1,2,3,4,9],
        [7,4,1,6,-3]
    ],
])
print("Array:",three_d_array)
print("Dimensions:", np.ndim(three_d_array))
print("Data Type:", three_d_array.dtype)
print("Shape: ",three_d_array.shape)

Array: [[[ 2  3  5  6  8]
  [ 1  2  0  4  9]
  [ 7  4  1  6 -1]]

 [[ 6  1  5  6  8]
  [ 1  2  3  4  9]
  [ 7  4  1  6 -3]]]
Dimensions: 3
Data Type: int64
Shape:  (2, 3, 5)


### Re-shaping an array : changing dimensions

In [20]:
the_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Original array: ",one_d_array)
the_array.shape = (3,4)
print("array re-shaped to (3,4): ",the_array)
the_array.shape = (4,3)
print("array re-shaped to (4,3): ",the_array)
the_array.shape = (2,3,2)
print("array re-shaped to (2,3,2): ",the_array)
the_array.shape = (2,3,2,1)
print("array re-shaped to (2,3,2,1): ",the_array)

Original array:  [2 3 5 6]
array re-shaped to (3,4):  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array re-shaped to (4,3):  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array re-shaped to (2,3,2):  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
array re-shaped to (2,3,2,1):  [[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]]


### Indexing and slicing

#### Slicing one dimensional array is very similar to the list

In [21]:

one_d_array = np.array([0,1,2,3,4,5,6])

In [22]:
print(one_d_array[-1]) # single element

6


In [23]:
print(one_d_array[[0,4,5]]) # multiple elements (Note this doesn't work for simple list)

[0 4 5]


In [24]:
print(one_d_array[0:7:2]) # range with step 2

[0 2 4 6]


In [25]:
print(one_d_array[6:0:-1]) # reverse

[6 5 4 3 2 1]


#### Slicing multi-dimensional array

In [26]:
two_d_array = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])

In [27]:
two_d_array[0]

array([0, 1, 2, 3])

In [28]:
two_d_array[0][2] # This creates an intermediate 1 d array and then index into it

2

In [29]:
# NOTE : the comma notation : selection of elements in that dimentions
# More performant way to access a single element in multi-dimensional array:
two_d_array[0,2] # 0th array : second element

2

In [30]:
two_d_array[1,[0,2,3]] # First array, elements at 0,2,3 positions

array([4, 6, 7])

In [31]:
two_d_array[[0,2]] # Array 0 and 2 : this is consistent with one_d_array

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [32]:
two_d_array[[0,2],1] # [two_d_array[0,1],two_d_array[2,1]]

array([1, 9])

In [33]:
two_d_array[[0,2],[1]] # [two_d_array[0,1],two_d_array[2,1]] - Same as above

array([1, 9])

In [34]:
two_d_array[[0,2],[0,1]] # [two_d_array[0,0],two_d_array[2,1]]

array([0, 9])

In [35]:
two_d_array[[0,-1],[0,-1]] # [two_d_array[0,0],two_d_array[-1,-1]] - first and last elements 

array([ 0, 11])

In [36]:
two_d_array[0:2] # It is same as two_d_array[0:2][:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [37]:
two_d_array[0:3:2] # odd rows

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [38]:
two_d_array[0:2,[0,3]] # 0th and 3rd elements from 0-2 arrays - selective elements from range of arrays

array([[0, 3],
       [4, 7]])

In [39]:
two_d_array[[0,2],1:3] # 1-3 elements from array 0 and array 2 - range of elements from selective arrays

array([[ 1,  2],
       [ 9, 10]])

In [40]:
two_d_array[0::2,1::2] # Even rows (arrays) odd columns (elements)

array([[ 1,  3],
       [ 9, 11]])

In [41]:
two_d_array[:,:] # All of all

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
three_d_array = np.arange(0,27).reshape(3,3,3)

In [43]:
print(three_d_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [44]:
print(three_d_array[0:2,2,1:3])

[[ 7  8]
 [16 17]]


In [45]:
print(three_d_array[0:2]) # It is same as three_d_array[0:2,:,:]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


<b>Important: Slicing creates a view instead of new objects, if views are modified, original objects get modified<b>

In [46]:
an_array = np.arange(0,8)
print("Before:",an_array)
view = an_array[2:4]
view[0] = 2000
print("After:",an_array)

Before: [0 1 2 3 4 5 6 7]
After: [   0    1 2000    3    4    5    6    7]


In [47]:
print(np.may_share_memory(an_array,view)) # The memory overlap for the two arrays

True


### Arrays of zeros and ones

In [48]:
print(np.zeros(5,dtype= int))

[0 0 0 0 0]


In [49]:
print(np.zeros((5,3),dtype= int))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [50]:
print(np.ones((3,2,1),dtype= int))

[[[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]]


In [51]:
model = np.array([3,5,2,3])
print(np.zeros_like(model))

[0 0 0 0]


In [52]:
print(np.zeros_like(np.arange(0,10).reshape(5,2)))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


### Array copy

In [53]:
original = np.arange(0,10)
duplicate = original.copy()
duplicate[0] = -1
print("original (not changed))",original)
print("duplicate",duplicate)

original (not changed)) [0 1 2 3 4 5 6 7 8 9]
duplicate [-1  1  2  3  4  5  6  7  8  9]


### Identitiy array : an array having value 1 at diagonal and 0 elsewhere 
When multiplied with another matrix, the result is another matrix

In [54]:
print(np.identity(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [55]:
print(np.identity(3,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [56]:
print(np.eye(4,dtype=int)) # same as identity but can work with assymetric arrays as well

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [57]:
print(np.eye(3,6,dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]


In [58]:
# k is the index for the diagonal, default value = 0 i.e. starting at element [0,0]
# negative value : starts from lower row
# positive value : starts from higher column
for i in range(-3,5):
    print("k =",i)
    print(np.eye(4,5,k=i,dtype=int))

k = -3
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]]
k = -2
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]
k = -1
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
k = 0
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]
k = 1
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
k = 2
[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
k = 3
[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
k = 4
[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
