## Numerical Operations

### Array and scaler operations

In [2]:
import numpy as np
the_array = np.array([3,5,6,1,4-1,6,-3])

In [4]:
print(the_array+3)

[6 8 9 4 6 9 0]


In [5]:
print(the_array-4)

[-1  1  2 -3 -1  2 -7]


In [6]:
print(the_array ** 2)

[ 9 25 36  1  9 36  9]


In [7]:
the_array += 2 # Array is re-assigned with the mutated version
print(the_array)

[ 5  7  8  3  5  8 -1]


In [3]:
print("Difference between successive numbers",np.diff(the_array))
print("Cumulitive sum",np.cumsum(the_array))

Difference between successive numbers [ 2  1 -5  2  3 -9]
Cumulitive sum [ 3  8 14 15 18 24 21]


### Multiple array operations

In [10]:
array_one = np.array([1,2,3,-3,2,-1])
array_two = np.array([2,1,4,3,-2,1])


In [11]:
print(array_one + array_two)

[3 3 7 0 0 0]


In [13]:
print(array_one // array_two)

[ 0  2  0 -1 -1 -1]


In [16]:
two_d_array_one = np.arange(0,9).reshape((3,3))
identitiy_array = np.ones_like(two_d_array_one)
print(two_d_array_one)
print(identitiy_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
print(two_d_array_one + identitiy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(two_d_array_one * (2*identitiy_array)) 
# Note is it element to element operation result[i][j] = a[i][j] + b[i][j] for all i and j

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


### dot product

In [42]:
print(np.dot(np.array([3]),np.array([4]))) # Note the result is always scalar

12


In [43]:
# 1D : every vector has 3 components below x,y,z , total dot product = Ax * Bx + Ay * By + Az * Bz
#    sum(A's progress in each of x,y,z direction * B's progress in each of x,y,z direction)

A = np.array([1,2,3])
B = np.array([1,2,3])

print(np.dot(A,B)) # 1*1 + 2*2 + 3*3

14


In [45]:
# 2D

# 2 vectors
X = np.array([
    [1,2,-1],
    [3,-2,1]
]);

# 5 vectors
Y = np.array([
    [3,1,2,1,2],
    [1,2,1,2,-1],
    [2,2,1,0,1]
])

# Do dot product of each pair of vector (one from A and another from B), total 2*5=10 pairs
# Represent each dot product as an element in the result arrays
# An array in the result for an array in first 2D array 
np.dot(X,Y)

array([[ 3,  3,  3,  5, -1],
       [ 9,  1,  5, -1,  9]])

Matrix multiplication :


Why dot product is rows of first matrix * colums of second matrix?

One argument : From the resultanat matrix it can be quickly deduced, how the perticular result was obtained. if i,j is the index of the element in resultant matrix, it is dot product of i'th row in first matrix and j'th column in second matrix.

The problem with having both matrices oriented the same way is that then we would have no system for determining which cell in the result matrix we should store the result of performing the dot product of two vectors.

![title](matrix_dot_product.jpg)

In [69]:
# 3D



# Shape : 4,2,3
A = np.array([[[ 0,  1,  2],
        [ 1,  1,  -1]],

       [[ 0,  2,  -1],
        [ 0, 0, 2]],

       [[2, 1, -1],
        [-1, -1, 2]],

       [[0, 2, -1],
        [2, 0, -1]]]);

# Vector level representation
# A = [[ A1,A2 ], [A3,A4], [A5,A6], [A7,A8] ]

print("A.shape = ",A.shape)

# Shape : 2,3,5
B = np.array([
        [[ 0,  -1,  -2,  0,  -1],
        [ 2,  2,  -1,  0,  0],
        [1, 0, 0, -1, 2]],

       [[-1, 1, 1, -1, 0],
        [2, 0, -1, 1, 2],
        [0, -1, 1, 0, 1]]
])

# Vector level representation
# B = [ [B1,B2,B3,B4,B5], [B6,B7,B8,B9,B10] ]

print("B.shape = ",B.shape)

print("dot(A,B).shape = ",np.dot(A,B).shape)

print("dot(A,B) = ",np.dot(A,B))



# DOT product vector representation : [[ A1,A2 ], [A3,A4], [A5,A6], [A7,A8] ] . [ [B1,B2,B3,B4,B5], [B6,B7,B8,B9,B10] ]


# The LHS 3D matrix Vector representation
#[
# [
#  A1,
#  A2
# ],
# [
#  A3,
#  A4
# ],
# [
#  A5,
#  A6
# ],
# [
#  A7,
#  A8
# ],
#]

# Conceptual dot product of two matrix in vector representation
#[
# [
#  [A1.[B1,B2,B3,B4,B5], A1.[B6,B7,B8,B9,B10]], # A1 with all the vectors in another matrix at all levels
#  [A2.[B1,B2,B3,B4,B5], A2.[B6,B7,B8,B9,B10]]  # A2 with all the vectors in another matrix at all levels
# ],
# [
#  [A3.[B1,B2,B3,B4,B5], A3.[B6,B7,B8,B9,B10]], 
#  [A4.[B1,B2,B3,B4,B5], A4.[B6,B7,B8,B9,B10]]
# ],
# [
#  [A5.[B1,B2,B3,B4,B5], A5.[B6,B7,B8,B9,B10]],
#  [A6.[B1,B2,B3,B4,B5], A6.[B6,B7,B8,B9,B10]]
# ],
# [
#  [A7.[B1,B2,B3,B4,B5], A7.[B6,B7,B8,B9,B10]],
#  [A8.[B1,B2,B3,B4,B5], A8.[B6,B7,B8,B9,B10]]
# ],
#]

#[
# [
#  [[A1.B1,A1.B2,A1.B3,A1.B4,A1.B5], [A1.B6,A1.B7,A1.B8,A1.B9,A1.B10]],
#  [[A2.B1,A2.B2,A2.B3,A2.B4,A2.B5], [A2.B6,A2.B7,A2.B8,A2.B9,A2.B10]],
# ],
# [
#  [[A3.B1,A3.B2,A3.B3,A3.B4,A3.B5], [A3.B6,A3.B7,A3.B8,A3.B9,A3.B10]],
#  [[A4.B1,A4.B2,A4.B3,A4.B4,A4.B5], [A4.B6,A4.B7,A4.B8,A4.B9,A4.B10]],
# ],
# [
#  [[A5.B1,A5.B2,A5.B3,A5.B4,A5.B5], [A5.B6,A5.B7,A5.B8,A5.B9,A5.B10]],
#  [[A6.B1,A6.B2,A6.B3,A6.B4,A6.B5], [A6.B6,A6.B7,A6.B8,A6.B9,A6.B10]],
# ],
# [
#  [[A7.B1,A7.B2,A7.B3,A7.B4,A7.B5], [A7.B6,A7.B7,A7.B8,A7.B9,A7.B10]],
#  [[A8.B1,A8.B2,A8.B3,A8.B4,A8.B5], [A8.B6,A8.B7,A8.B8,A8.B9,A8.B10]],
# ],
#]


# An array for each vector in LHS matrix and an array of vectors in RHS matrix

#[
# [
#  [
#    [A1.B1,A1.B2,A1.B3,A1.B4,A1.B5],
#    [A1.B6,A1.B7,A1.B8,A1.B9,A1.B10]
#  ],
#  [
#    [A2.B1,A2.B2,A2.B3,A2.B4,A2.B5],
#    [A2.B6,A2.B7,A2.B8,A2.B9,A2.B10]
#  ],
# ],
#
# [
#  [
#    [A3.B1,A3.B2,A3.B3,A3.B4,A3.B5],
#    [A3.B6,A3.B7,A3.B8,A3.B9,A3.B10]
#  ],
#  [
#    [A4.B1,A4.B2,A4.B3,A4.B4,A4.B5],
#    [A4.B6,A4.B7,A4.B8,A4.B9,A4.B10]
#  ],
# ],
#
# [
#  [
#    [A5.B1,A5.B2,A5.B3,A5.B4,A5.B5],
#    [A5.B6,A5.B7,A5.B8,A5.B9,A5.B10]
#  ],
#  [
#    [A6.B1,A6.B2,A6.B3,A6.B4,A6.B5],
#    [A6.B6,A6.B7,A6.B8,A6.B9,A6.B10]
#  ],
# ],
#
# [
#  [
#    [A7.B1,A7.B2,A7.B3,A7.B4,A7.B5],
#    [A7.B6,A7.B7,A7.B8,A7.B9,A7.B10]
#  ],
#  [
#    [A8.B1,A8.B2,A8.B3,A8.B4,A8.B5],
#    [A8.B6,A8.B7,A8.B8,A8.B9,A8.B10]
#  ],
# ],
#]


#      [[[[ 4,  2, -1, -2,  4],
#         [ 2, -2,  1,  1,  4]],
#
#        [[ 1,  1, -3,  1, -3],
#         [ 1,  2, -1,  0,  1]]],
#
#
#       [[[ 3,  4, -2,  1, -2],
#         [ 4,  1, -3,  2,  3]],
#
#        [[ 2,  0,  0, -2,  4],
#         [ 0, -2,  2,  0,  2]]],
#
#
#       [[[ 1,  0, -5,  1, -4],
#         [ 0,  3,  0, -1,  1]],
#
#        [[ 0, -1,  3, -2,  5],
#         [-1, -3,  2,  0,  0]]],
#
#
#       [[[ 3,  4, -2,  1, -2],
#         [ 4,  1, -3,  2,  3]],
#
#        [[-1, -2, -4,  1, -4],
#         [-2,  3,  1, -2, -1]]]]

# Dimensions calculations for 3D matrix dot product result: 
# First two dimensions of LHS matrix (The dot product start with the lowest dimension - which is a vector) + 
# First dimension of RHS matrix (as each vector in LHS is multiplied with each vector array in RHS) + 
# Last dimension of RHS matric (This decides the length of row in the product)

A.shape =  (4, 2, 3)
B.shape =  (2, 3, 5)
dot(A,B).shape =  (4, 2, 2, 5)
dot(A,B) =  array([[[[ 4,  2, -1, -2,  4],
         [ 2, -2,  1,  1,  4]],

        [[ 1,  1, -3,  1, -3],
         [ 1,  2, -1,  0,  1]]],


       [[[ 3,  4, -2,  1, -2],
         [ 4,  1, -3,  2,  3]],

        [[ 2,  0,  0, -2,  4],
         [ 0, -2,  2,  0,  2]]],


       [[[ 1,  0, -5,  1, -4],
         [ 0,  3,  0, -1,  1]],

        [[ 0, -1,  3, -2,  5],
         [-1, -3,  2,  0,  0]]],


       [[[ 3,  4, -2,  1, -2],
         [ 4,  1, -3,  2,  3]],

        [[-1, -2, -4,  1, -4],
         [-2,  3,  1, -2, -1]]]])


### Actual matrices

In [81]:
# matrices can be constructed from 2D arrays like
A = np.arange(0,10).reshape(2,5)
AM = np.mat(A)
print(AM)
B = np.eye(5,6,k=1,dtype=int)
BM = np.mat(B)
print(BM)

print(AM*BM) # This is actual matrix multiplication (dot product) and not product of 2D arrays

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[[0 0 1 2 3 4]
 [0 5 6 7 8 9]]


### Array comparisions

In [85]:
A = np.array([[1,2],[3,4],[2,1]])
B = np.array([[1,1],[1,4],[3,1]])

C = (A == B)
print(C)



[[ True False]
 [False  True]
 [False  True]]
[[False  True]
 [ True False]
 [False False]]


In [86]:
print(A > B)

[[False  True]
 [ True False]
 [False False]]


In [87]:
print(A >= B)

[[ True  True]
 [ True  True]
 [False  True]]


In [89]:
print ( np.array_equal(A,B)) # Compare overall

False


### Logical operators

In [96]:


A = np.array([[True,False],[False,True]])
B = np.array([[True,True],[False,False]])

[[ True  True]
 [ True  True]]


In [91]:
print(np.logical_or(A,B))

[[ True  True]
 [False  True]]


In [92]:
print(np.logical_and(A,B))

[[ True False]
 [False False]]


In [93]:
print(np.logical_xor(A,B))

[[False  True]
 [False  True]]


In [98]:
print(np.logical_or(A > B,A <= B))

[[ True  True]
 [ True  True]]


### Broadcasting : array shapes are matched by repeating singleton dimension elements 
#### For 2D it could be : vertically or/and horizontally
#### Note : the shapes of the two arrays involved can have length 1 for any dimension, then that is multiplied by n at the other side
#### E.g.  (m) * (1) : RHS is made m so (m) * (1) becomes (m)*(m)
#### E.g.  (3,3) * (3,1) : RHS is made (3,3) for broadcasting
#### E.g.  (2) * (3,2) : LHS is made (2) -> (1,2) -> (3,2) to match RHS shape
#### E.g.  (3,1,2) * (3,3,1) : LHS is made (3,3,2) and RHS is made (3,3,2) 


In [100]:
# Normal scalar operation
print(np.array([1,2,3])+1) 

[2 3 4]


In [101]:
# Broadcasting same as [1,2,3] + [1,1,1] : RHS is repeated LHS array size : (1) -> (3)
print(np.array([1,2,3])+np.array([1])) 

[2 3 4]


In [140]:
print(np.array([1,2,3,4])+np.array([1,2])) # This is not possible  (4) or (2) cannot be converted to each other

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [114]:
# Broadcasting same as np.arange(0,9).reshape(3,3)+[[1,2,3],[1,2,3],[1,2,3]] : first dimension repeated : (1,3)->(3,3)
print(np.arange(9).reshape(3,3)+np.array([1,2,3])) 

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [113]:
# Broadcasting same as np.arange(0,9).reshape(3,3)+[[1,1,1],[2,2,2],[3,3,3]] : second dimension repeated : (3,1)->(3,3)
print(np.arange(9).reshape(3,3)+np.array([[1],[2],[3]]))

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [112]:
# Double broadcasting : same as np.arange(0,9).reshape(3,3)+[[1,1,1],[1,1,1],[1,1,1]] : 
# both dimensions repeated : (1)->(3,3)
print(np.arange(9).reshape(3,3)+np.array([1]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
# Double broadcasting : same as np.arange(0,9).reshape(3,3)+[[1,1,1],[1,1,1],[1,1,1]] : 
# both dimensions repeated : (1,1)->(3,3)
print(np.arange(9).reshape(3,3)+np.array([[1]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [109]:
# Broadcasting on LHS as well as RHS : same as [[0,1,2],[0,1,2],[0,1,2]] + [[0,0,0],[1,1,1],[2,2,2]]
# (1,3) -> (3,3) AND (3,1) -> (3,3)
print(np.array([0,1,2])+np.array([[0],[1],[2]]))

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 3D broadcasting

In [126]:

D3 = np.arange(12).reshape(2,3,2)
print("D3=",D3)
D2 = np.arange(6).reshape(3,2) # Will be broadcasted as (3,2)->(2,3,2) : (3,2) is repeated twice
print("\nD2=",D2)
print("\nD3*D2=",D3*D2)

D3= [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

D2= [[0 1]
 [2 3]
 [4 5]]

D3*D2= [[[ 0  1]
  [ 4  9]
  [16 25]]

 [[ 0  7]
  [16 27]
  [40 55]]]


In [123]:
D3 = np.arange(12).reshape(2,3,2)
print("D3=",D3)
D1 = [1,2] # Will be broadcasted as (2)->(2,3,2) : (2) is repeated thrice [[1,2],[1,2],[1,2]] and then repeated twice
print("\nD1=",D1)
print("\nD3*D1=",D3*D1)

D3= [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

D1= [1, 2]

D3*D1= [[[ 0  2]
  [ 2  6]
  [ 4 10]]

 [[ 6 14]
  [ 8 18]
  [10 22]]]


In [133]:
D3 = np.arange(12).reshape(2,3,2)
print("D3=",D3)
D2 = [[0],[1],[2]] # Will be broadcasted as (3,1) -> (3,2) -> (2,3,2)
print("\nD2=",D2)
print("\nD3*D2=",D3*D2)

D3= [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

D2= [[0], [1], [2]]

D3*D2= [[[ 0  0]
  [ 2  3]
  [ 8 10]]

 [[ 0  0]
  [ 8  9]
  [20 22]]]


In [136]:
A = np.arange(12).reshape(2,3,2)
print("A=",A)
B = [[[0],[1],[2]],[[3],[4],[5]]] # Will be broadcasted as (2,3,1) -> (2,3,2) : [[[0,0],[1,1],[2,2]],[[3,3],[4,4],[5,5]]]
print("\nB=",B)
print("\nA*B=",A*B)

A= [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

B= [[[0], [1], [2]], [[3], [4], [5]]]

A*B= [[[ 0  0]
  [ 2  3]
  [ 8 10]]

 [[18 21]
  [32 36]
  [50 55]]]


In [138]:
A = np.arange(12).reshape(2,3,2)
print("A=",A)
B = [[[0,1]],[[2,3]]] # Will be broadcasted as (2,1,2) -> (2,3,2) : [[[0,1],[2,3],[4,5]],[[0,1],[2,3],[4,5]]]
print("\nB=",B)
print("\nA*B=",A*B)

A= [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

B= [[[0, 1]], [[2, 3]]]

A*B= [[[ 0  1]
  [ 0  3]
  [ 0  5]]

 [[12 21]
  [16 27]
  [20 33]]]


In [139]:
#(3,1,2) * (1,2,1)
A = np.arange(6).reshape(3,1,2) # [[[0,1]],[[2,3]],[[4,5]]] -> [[[0,1],[0,1]],[[2,3],[2,3]],[[4,5],[4,5]]]
print("A=",A)
B = np.arange(2).reshape(1,2,1) # [[[0],[1]]] -> [[[0,0],[1,1]]] -> [[[0,0],[1,1]],[[0,0],[1,1]],[[0,0],[1,1]]]
  
print("\nB=",B)
print("\nA*B=",A*B)

A= [[[0 1]]

 [[2 3]]

 [[4 5]]]

B= [[[0]
  [1]]]

A*B= [[[0 0]
  [0 1]]

 [[0 0]
  [2 3]]

 [[0 0]
  [4 5]]]
