In [1]:
import numpy as np

### Random float between 0 to 1

In [6]:
# single value
np.random.random()

0.5638084189017718

In [5]:
# as array
print(np.random.random(10))

[0.81493786 0.08485511 0.0776805  0.15531197 0.48518124 0.32922354
 0.12256783 0.00419276 0.70167108 0.81905979]


In [8]:
# as multidimensional array
print(np.random.random((3,4,5)))

[[[0.66237688 0.30744371 0.82377537 0.52497615 0.75839555]
  [0.98395756 0.06603815 0.933216   0.78262404 0.67647749]
  [0.80052682 0.37320875 0.77657412 0.46328965 0.47015138]
  [0.57597436 0.87257466 0.50859737 0.10254686 0.91128671]]

 [[0.63028405 0.02217668 0.33582141 0.40138445 0.2536396 ]
  [0.05249009 0.5523969  0.61584198 0.02924334 0.59803534]
  [0.54293188 0.15891522 0.7626963  0.03620698 0.84054286]
  [0.7675408  0.19278597 0.97599986 0.24516262 0.86922716]]

 [[0.97179154 0.54157765 0.90838837 0.73604841 0.3559766 ]
  [0.60497297 0.82216136 0.71820455 0.5365716  0.28919361]
  [0.43519605 0.58783988 0.64953648 0.88301668 0.40969486]
  [0.47365103 0.83934929 0.30609199 0.03542741 0.6630026 ]]]


In [12]:
# An array with random floats between 5 and 10

print(5+5*np.random.random((5,3)))

[[9.48320184 8.1312598  8.12483397]
 [6.37146627 8.95898071 9.50954482]
 [6.18813972 8.91180492 9.23942009]
 [5.64104354 8.00952012 5.15291021]
 [8.10702303 9.91929651 7.06533398]]


In [15]:
# array of random numbers with sum 1

numbers = np.random.random(10)

numbers /= numbers.sum()

print(numbers)

print(numbers.sum())

[0.02559759 0.22822578 0.04448121 0.09084176 0.09879452 0.15972954
 0.0142107  0.12008929 0.2006864  0.01734322]
1.0


### Random integers

In [16]:
# single number : exclusive of the end
np.random.randint(20)

5

In [25]:
# number in a range

np.random.randint(1,7)

2

In [26]:
# An array of specific size

np.random.randint(1,10,size=(2,3,2))

array([[[6, 1],
        [3, 6],
        [5, 5]],

       [[6, 5],
        [3, 7],
        [2, 3]]])

### Random choice

In [34]:
days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']


# single choice
np.random.choice(days)

'Thursday'

In [33]:
# Choice array
np.random.choice(days,size=(2,3))

array([['Wednesday', 'Thursday', 'Wednesday'],
       ['Saturday', 'Saturday', 'Saturday']], dtype='<U9')

In [38]:
# Choice with no repeat

print(np.random.choice(days,size=(7),replace=False))

['Tuesday' 'Wednesday' 'Thursday' 'Saturday' 'Monday' 'Sunday' 'Friday']


### Random Sample

In [42]:
# random_sample is an alias to random

print(np.random.random is np.random.random_sample)

True


### Weighted randoms

In [51]:
# p is respective probability of the population

np.random.choice(days,p=[0.04,0.04,0.04,0.04,0.04,0.4,0.4])

'Saturday'

In [63]:
# tesing probability
prob_map = { day:0 for day in days }
for _ in range(10000):
    day = np.random.choice(days,p=[0.04,0.04,0.04,0.04,0.04,0.4,0.4])
    prob_map[day]+=(1/10000)
    
print(prob_map)

{'Monday': 0.04030000000000013, 'Tuesday': 0.03610000000000001, 'Wednesday': 0.037800000000000056, 'Thursday': 0.040200000000000125, 'Friday': 0.03860000000000008, 'Saturday': 0.4032999999999719, 'Sunday': 0.40369999999997186}


In [64]:
# Multiple values

print(np.random.choice(days,p=[0.04,0.04,0.04,0.04,0.04,0.4,0.4],size=(2,3)))

[['Saturday' 'Sunday' 'Saturday']
 ['Saturday' 'Saturday' 'Saturday']]


In [71]:
# Multiple value without repeat/replace

print(np.random.choice(days,p=[0.04,0.04,0.04,0.04,0.04,0.4,0.4],size=(2,3),replace=False))

[['Tuesday' 'Wednesday' 'Sunday']
 ['Saturday' 'Monday' 'Thursday']]


### Cartesian choice

In [91]:
person = (['girl','boy','man','woman','lady'],[0.5,0.3,0.1,0.05,0.05])
shirt_color = (['red','green','yellow','white','blue','orange'],[0.1,0.2,0.2,0.3,0.1,0.1])
number = (np.arange(2,5),[0.5,0.25,0.25])
animal_color = (['black','white','grey','orange'],[0.2,0.3,0.4,0.1])
animal = (['cat','dog','cow','goat','horse'],[0.4,0.5,0.04,0.04,0.02])

def cartesian_choice(*iterables):
        
    return [np.random.choice(item[0],p=item[1]) for item in iterables]

choices = cartesian_choice(person,shirt_color,number,animal_color,animal)

print("The %s in %s shirt has %d %s %ss"% tuple(choices))
    

The girl in yellow shirt has 4 grey dogs
