In [4]:
import numpy as np

### Random float between 0 to 1

In [6]:
# single value
np.random.random()

0.5638084189017718

In [15]:
# as array
print(np.random.random(10))

[-0.268543   -0.66267821  0.49675826 -0.41425815 -0.42774245 -1.9335648
 -2.32149652 -0.47771276 -0.06103394 -1.9361826   0.76164688 -1.49751763
  0.03556214 -1.5933038   0.39007701  1.47656219  0.07613076 -0.72604849
 -0.35180222 -0.86696747  0.89037022 -0.49355783 -0.23520914  0.09063762
  0.23626988 -0.95523494  0.96235974 -1.68508516  0.16943335  1.05720206]


In [10]:
# as multidimensional array
print(np.random.random((3,4,5)))

[[[0.07006442 0.23070622 0.38741443 0.23550553 0.80217595]
  [0.56977969 0.60258589 0.8373512  0.04971338 0.96688684]
  [0.39568845 0.40924032 0.5602141  0.48896213 0.20863573]
  [0.12700544 0.02331006 0.78923924 0.76917428 0.54076428]]

 [[0.03967166 0.28794473 0.80776434 0.59253191 0.73629691]
  [0.24744529 0.76120063 0.17648242 0.70497473 0.39654903]
  [0.62894097 0.32621511 0.20485733 0.19145658 0.66494359]
  [0.54375927 0.40118359 0.80284755 0.48905492 0.19916691]]

 [[0.74082419 0.54797219 0.45167609 0.07431955 0.32821674]
  [0.76430824 0.62051288 0.44386829 0.3022082  0.48285068]
  [0.74593872 0.70166745 0.5948375  0.01094624 0.0468124 ]
  [0.67681506 0.09065698 0.02232496 0.34883398 0.88803832]]]


In [11]:
# An array with random floats between 5 and 10

print(5+5*np.random.random((5,3)))

[[9.29754741 8.355361   5.37308713]
 [8.83495435 6.30260187 8.12763388]
 [7.77674906 5.82404328 6.37989514]
 [6.96155634 9.16234465 8.06053199]
 [8.29748826 5.59647034 5.27756243]]


In [15]:
# array of random numbers with sum 1

numbers = np.random.random(10)

numbers /= numbers.sum()

print(numbers)

print(numbers.sum())

[0.02559759 0.22822578 0.04448121 0.09084176 0.09879452 0.15972954
 0.0142107  0.12008929 0.2006864  0.01734322]
1.0


### Random integers

In [16]:
# single number : exclusive of the end
np.random.randint(20)

5

In [25]:
# number in a range

np.random.randint(1,7)

2

In [26]:
# An array of specific size

np.random.randint(1,10,size=(2,3,2))

array([[[6, 1],
        [3, 6],
        [5, 5]],

       [[6, 5],
        [3, 7],
        [2, 3]]])

In [16]:
# Normal distribution (Bell curve, more probability for values around mean, lesser to extreme ends )

np.random.randn(20)

array([ 0.69460668, -0.13464202, -0.8233955 , -0.40702111,  0.34554403,
        0.0061588 , -0.34825507, -2.27256165,  0.33593302, -0.36076423,
       -0.20852098,  0.51608668,  0.4597924 ,  1.13983313,  1.26197621,
       -0.86952285, -0.05019714,  0.06843893,  0.450219  ,  0.81675458])

### Random choice

In [34]:
days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']


# single choice
np.random.choice(days)

'Thursday'

In [33]:
# Choice array
np.random.choice(days,size=(2,3))

array([['Wednesday', 'Thursday', 'Wednesday'],
       ['Saturday', 'Saturday', 'Saturday']], dtype='<U9')

In [38]:
# Choice with no repeat

print(np.random.choice(days,size=(7),replace=False))

['Tuesday' 'Wednesday' 'Thursday' 'Saturday' 'Monday' 'Sunday' 'Friday']


### Random Sample

In [42]:
# random_sample is an alias to random

print(np.random.random is np.random.random_sample)

True


### Weighted randoms

In [51]:
# p is respective probability of the population

np.random.choice(days,p=[0.04,0.04,0.04,0.04,0.04,0.4,0.4])

'Saturday'

In [63]:
# tesing probability
prob_map = { day:0 for day in days }
for _ in range(10000):
    day = np.random.choice(days,p=[0.04,0.04,0.04,0.04,0.04,0.4,0.4])
    prob_map[day]+=(1/10000)
    
print(prob_map)

{'Monday': 0.04030000000000013, 'Tuesday': 0.03610000000000001, 'Wednesday': 0.037800000000000056, 'Thursday': 0.040200000000000125, 'Friday': 0.03860000000000008, 'Saturday': 0.4032999999999719, 'Sunday': 0.40369999999997186}


In [64]:
# Multiple values

print(np.random.choice(days,p=[0.04,0.04,0.04,0.04,0.04,0.4,0.4],size=(2,3)))

[['Saturday' 'Sunday' 'Saturday']
 ['Saturday' 'Saturday' 'Saturday']]


In [71]:
# Multiple value without repeat/replace

print(np.random.choice(days,p=[0.04,0.04,0.04,0.04,0.04,0.4,0.4],size=(2,3),replace=False))

[['Tuesday' 'Wednesday' 'Sunday']
 ['Saturday' 'Monday' 'Thursday']]


### Cartesian choice

In [91]:
person = (['girl','boy','man','woman','lady'],[0.5,0.3,0.1,0.05,0.05])
shirt_color = (['red','green','yellow','white','blue','orange'],[0.1,0.2,0.2,0.3,0.1,0.1])
number = (np.arange(2,5),[0.5,0.25,0.25])
animal_color = (['black','white','grey','orange'],[0.2,0.3,0.4,0.1])
animal = (['cat','dog','cow','goat','horse'],[0.4,0.5,0.04,0.04,0.02])

def cartesian_choice(*iterables):
        
    return [np.random.choice(item[0],p=item[1]) for item in iterables]

choices = cartesian_choice(person,shirt_color,number,animal_color,animal)

print("The %s in %s shirt has %d %s %ss"% tuple(choices))
    

The girl in yellow shirt has 4 grey dogs


In [3]:
np.random.randn(2,6)

array([[ 0.86605639,  0.1911869 ,  0.37318966,  1.61821503,  0.85651128,
        -0.37948731],
       [ 0.50718148,  1.30387803,  0.54408291, -1.46095749,  0.74356016,
         0.96771299]])